### ISSUE TITLE
翻訳後にページが見れなくなる

### ISSUE THREAD

**Issue by cyborgninja** [WOVNio/wovnrb#1]
http://favy.tips/
(wovnrb 0.1.70)

1. フッターのリンクで別言語に翻訳する
　(ex: es.favy.tips)
2. 記事詳細へのリンクを押す
　(ex: es.favy.tips/topics/61)
3. Internal server error が出てしまう

以下、production.logです。
[b0bc7ed8-ab45-4fc9-8dd6-2f8229a6ac1a] method=GET path=/topics/58 format=html controller=www_domain/topics action=show status=200 duration=130.81 view=84.06 db=43.46 host=favy.tips remote_addr=172.31.8.129

**Comment by cyborgninja** [comment]
apacheのerror.log

App 1617 stderr: [ 2015-11-10 11:59:26.6709 1666/0x000000025717f8(Worker 1) utils.rb:72 ]: *** Exception URI::InvalidURIError in Rack application object (bad URI(is not URI?): http://www.facebook.com/sharer.php?u=http://favy.tips/topics/50&amp;t=Gourmet Tofu World: Vegetarian-Friendly Japanese Food is Here!) (process 1666, thread 0x000000025717f8(Worker 1)):
App 1617 stderr: 	from /usr/local/lib/ruby/2.1.0/uri/common.rb:176:in `split'
App 1617 stderr: 	from /usr/local/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
App 1617 stderr: 	from /usr/local/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
App 1617 stderr: 	from /usr/local/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/wovnrb-0.1.70/lib/wovnrb.rb:70:in `add_lang_code'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/wovnrb-0.1.70/lib/wovnrb.rb:127:in `block (2 levels) in switch_lang'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/wovnrb-0.1.70/lib/wovnrb.rb:125:in `block in switch_lang'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/rack-1.5.3/lib/rack/body_proxy.rb:31:in `each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/rack-1.5.3/lib/rack/body_proxy.rb:31:in `each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/rack-1.5.3/lib/rack/body_proxy.rb:31:in `each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/rack-1.5.3/lib/rack/body_proxy.rb:31:in `each'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/wovnrb-0.1.70/lib/wovnrb.rb:119:in `switch_lang'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/wovnrb-0.1.70/lib/wovnrb.rb:54:in `call'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:514:in `call'
App 1617 stderr: 	from /home/deploy/.bundler/favy_global/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:144:in `call'
App 1617 stderr: 	from /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.46/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 1617 stderr: 	from /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.46/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 1617 stderr: 	from /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.46/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 1617 stderr: 	from /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.46/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by cyborgninja** [comment]
appのerror.log

[error] [client 172.31.28.229] Premature end of script headers: topics, referer: http://zh-cht.favy.tips/

**Comment by cyborgninja** [comment]
↑すべて、
http://zh-cht.favy.tips/topics/50
のURLにアクセスしてInternal server errorを出したときのログをコピペしてます。

**Comment by jsand-minimal** [comment]
再現出来まして、上のバグ直しました。

今同じところで色なテストやっていますけど、今のフィックスを0.1.71番に入れてrubygemsにuploadしました
