### ISSUE TITLE
Can not install Wovnrb

### ISSUE THREAD

**Issue by DucNguyenVan** [WOVNio/wovnrb#100]
Hi Wovn Team,
Sorry about my english.
i was following the document(README.md) to set up Wovnrb for my project.
But it not work! and no error messages in server
<img width="897" alt="2018-01-29 15 03 49" src="https://user-images.githubusercontent.com/4339187/35495725-a508496a-0505-11e8-9f95-3902a86b93e5.png">

config/application.rb
```ruby
    config.wovnrb = {
      :project_token => 'xxxx',
      :url_pattern => 'path',
      :default_lang => 'ja'
    }
```

My environment:
```
% bundle show wovn
vendor/bundle/gems/wovnrb-0.2.30

% bundle show rails                                                                    
vendor/bundle/gems/rails-4.1.4

% ruby -v 
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

```
I tested on many devices and many older Wovnrb version, but it not work.
What did I missed?
Thanks!

**Comment by jsand-minimal** [comment]
Hi,

Sorry for the delayed response! Your current config file is incorrect. You need to set a valid project_token. Create a project at https://wovn.io and then you can get the project token from your overview.

![image](https://user-images.githubusercontent.com/7220646/35803766-55c95cc8-0ab8-11e8-98b6-3a6a640dd76b.png)

Please let me know if you need any more help.

**Comment by DucNguyenVan** [comment]
Hi, 
Thank you for your response
actually I was set the project token as you said.
I want to hide my project token so I changed it to "xxxx" at my issue.(sorry for this)
Anyway, I found out the problem.
Wovn is not compatible with my rack profiler setup.
I have changed 
```
Rails.application.middleware.delete(Rack::MiniProfiler)
Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
```
to 
```
Rails.application.middleware.swap(Rack::Deflater, Rack::MiniProfiler)
Rails.application.middleware.swap(Rack::MiniProfiler, Rack::Deflater)
```
and it worked!
Hope this help
