### ISSUE TITLE
Update logic of wovn_disable params

### ISSUE THREAD

**Issue by DucNguyenVan** [WOVNio/wovnrb#106]
Hi WOVN team,
About wovn disable feature,https://github.com/WOVNio/wovnrb/pull/98
I think it could be better if we return immediately after check wovn_disable is true
it will increase the speed of WOVNrb.
like this
```rb
  class Interceptor
    def call(env)
      request = Rack::Request.new(env)
      if request.params['wovn_disable'] == true
        return @app.call(env)
      end
    end
  end
```

what do you think?
Thank you

**Comment by jsand-minimal** [comment]
Hi,

The reason we don't return immediately is because we want to make sure we run `headers.out(res_headers)` before returning. Because this is shared logic, I didn't want to duplicate it and increase the possibility of introducing bugs when code is modified in the future.
