### ISSUE TITLE
Support custom language code

### ISSUE THREAD

**Issue by yuyuvn** [WOVNio/wovnrb#153]
We making a service which support multi clients.
Each client use a different wovn token and default language.

process is behind rack rewrite, something like this:
origin REQUEST_URI: `/en/hoge`
rewrite REQUEST_URI: `/pages/2`

when it get language code from REQUEST_URI, it's always read `/pages/2`, not `/en/hoge` so it can't read correct language.
https://github.com/WOVNio/wovnrb/blob/master/lib/wovnrb/headers.rb#L88

currentlly we have to use this monkey patch to make it work:
https://github.com/basicinc/wovnrb/commit/86474f87f058e8fde4f35c1ffdb77ddf4ddf5c7c

**Comment by bstewart00** [comment]
What does your `rails middleware` look like? Wovnrb::Interceptor should be placed before Rack::Rewrite. Wovnrb is expected to be placed such that REQUEST_URI contains the language code in the url e.g. `/en/hoge`.

**Comment by yuyuvn** [comment]
@bstewart00 

our middleware:

```
 Rack::UTF8Sanitizer,
 Rack::HandleBadEncodingMiddleware,
 Rack::Rewrite,
 Homeup::Application,
 Raven::Rack,
 Rack::MiniProfiler,
 Rack::Sendfile,
 ActionDispatch::Static,
 ActionDispatch::Executor,
 Rack::Runtime,
 Rack::MethodOverride,
 ActionDispatch::RequestId,
 RequestStore::Middleware,
 ActionDispatch::RemoteIp,
 Rails::Rack::Logger,
 ActionDispatch::ShowExceptions,
 WebConsole::Middleware,
 ActionDispatch::DebugExceptions,
 BetterErrors::Middleware,
 ActionDispatch::Reloader,
 ActionDispatch::Callbacks,
 ActiveRecord::Migration::CheckPending,
 ActionDispatch::Cookies,
 ActionDispatch::Session::CookieStore,
 ActionDispatch::ContentSecurityPolicy::Middleware,
 Rack::Head,
 Rack::ConditionalGet,
 Rack::ETag,
 Rack::TempfileReaper,
 Warden::Manager,
 Remotipart::Middleware,
 Rack::Deflater,
 Wovnrb::Interceptor,
 Mailjet::Rack::Endpoint
```

config.ru:
```ruby
require 'rack/rewrite'
require 'rack/utf8_sanitizer'
require ::File.expand_path('../lib/rack/handle_bad_encoding_middleware.rb', __FILE__)
require ::File.expand_path('../config/environment', __FILE__)

use Rack::UTF8Sanitizer
use Rack::HandleBadEncodingMiddleware
use Rack::Rewrite

run Rails.application
```

**Comment by bstewart00** [comment]
If you are using Rack::Deflater, then wovnrb will be inserted after it by default since we need to read the uncompressed response.

So I would consider moving 
```
 Rack::Deflater,
 Wovnrb::Interceptor,
```
to be above `Rack::Rewrite` in your middleware stack so that wovnrb sees the original request URI. Note that you may need to move `ActionDispatch::Static` as well depending on how you serve static assets.
