### ISSUE TITLE
メインドメイン部分が書き換わってしまう

### ISSUE THREAD

**Issue by cyborgninja** [WOVNio/wovnrb#2]
http://favy.tips/
(wovnrb 0.1.71)

1. フッターのリンクで別言語に翻訳する (ex: es.favy.tips)
2. フッターのEnglishのリンクを選択する
3. favy.tipsに飛ぶはずが、es.favy.tipsのままになる  
 (1で zh-chs.favy.tips を選択したら 2の飛び先が zh-chs.favy.tips になる)

尚、リンク部分のViewファイルのソースは以下。
```
[haml]
(省略)
%ul
  %li= link_to "English", "//favy.tips", class: "en"
  %li= link_to "簡体中文", "//zh-chs.favy.tips", class: "zh-chs"
  %li= link_to "繁体中文", "//zh-cht.favy.tips", class: "zh-cht"
(省略)
```

**Comment by jsand-minimal** [comment]
この問題を解決する為に１つ提案なのですが、
言語がチェンジされる度にhrefプロパティとコンテンツ（コンテンツが指定された場合のみ）を書き換え、
除去する方法があるのですがいかがでしょうか。
※この方法であれば、新しく選択された言語が都度デフォルトとして登録される為。

**Comment by jsand-minimal** [comment]
<a wovn-ignore></a>

**Comment by cyborgninja** [comment]
skypeで話させてもらって納得です。
・基本的にリンクは全部今wovnrbが置き換えてしまう
・特定のclassかidで囲うことで置き換わらないエリアを作れるようにする
