### ISSUE TITLE
[free trials]Culturefriend: /en was add while click on some of the page's link

### ISSUE THREAD

**Issue by Shojigo** [WOVNio/wovnrb#25]
reply by: hopefully soon
reason: its kind of critical for them
url:http://culturefriends.jp/en
detail: for example when you click [the event to see] link, the url became [http://culturefriends.jp/en/enevents] whihc obviously this page doesnt exist,
the right url for the link should be http://culturefriends.jp/en/events
step to reproduce:
1. go to the page
2. click on the [the event to see]button.
3. page was not found.

**Comment by jsand-minimal** [comment]
complete by: 4/20

reason: serious bug

If you load the page in English, it flashes Japanese (backend isn't translating it). And the page source has "/enevents#event-list" as the link, so WOVNrb is setting it wrong as well.

**Comment by jsand-minimal** [comment]
Issue moved to [WOVNio/equalizer #591](https://github.com/WOVNio/equalizer/issues/591) via [**ZenHub.io**](https://www.zenhub.io/)
