### ISSUE TITLE
通常の相対パスのリンク先が変わってしまう

### ISSUE THREAD

**Issue by cyborgninja** [WOVNio/wovnrb#3]
http://favy.tips/
(wovnrb 0.1.74)

1. http://favy.tips/topics/50 などの下層ページへアクセスする
2. フッターのリンクで別言語に翻訳する (ex: es.favy.tips)
3. ページ内の右にあるアクセスランキングなどにあるリンクをクリックする
(http://favy.tips/topics/50/topics/54 などへアクセスしてしまう)

1,2は順不同。
3のところで、相対パスのリンクが書き換わっていて、current_urlに相対のパスがついてしまう模様。

```
<a href="/topics/54">...
```
のようになっているリンクが、翻訳後のページで、
```
<a href="http://zh-cht.favy.tips/topics/50/topics/54">...
```
のようなリンクになってしまうようです。
(http://zh-cht.favy.tips/topics/50/ がcurrent_url)

**Comment by jsand-minimal** [comment]
バージョン0.1.75で直しました
