### ISSUE TITLE
スマホでアクセスするとレスポンシブにならない

### ISSUE THREAD

**Issue by cyborgninja** [WOVNio/wovnrb#4]
http://favy.tips/
(wovnrb 0.1.75)

1. スマートフォンでアクセスする(レスポンシブなviewが表示される)
2. フッターのリンクで別言語に翻訳する (ex: es.favy.tips)
とすると、スマートフォン用のviewではなくPCモードの画面が表示される。

```css
@media screen and (min-width: 769px){
```
のCSS制御のみしかやっていません(UserAgentなどでの振り分けは使っていません)
CSSのmedia screenが無視されるようです？

**Comment by jsand-minimal** [comment]
原因分かるようになりましたが、直すのはちょっと時間かかりますので(明日か明後日まで直すはず)hotfixを入れましてバージョン0.1.76で起こらないはずです。

一応バージョン0.1.76はmetaタグは対応していないです。ご迷惑かけて申し訳ないです。

**Comment by jsand-minimal** [comment]
この問題はもともとGEMのバグじゃなくて、WOVN.ioのバグでしたので。そっちを直しまして、この問題は無くなりましたはずです。

0.1.77からmetaの対応また戻しました。
