### ISSUE TITLE
リンク先がおかしくなった

### ISSUE THREAD

**Issue by cyborgninja** [WOVNio/wovnrb#5]
http://wasa-bi.com/
フッターにある静的なリンクが、
```
<li><a class="en" href="//wasa-bi.com" wovn-ignore="">English</a></li>
<li><a class="zh-chs" href="//zh-chs.wasa-bi.com">簡体中文</a></li>
<li><a class="zh-cht" href="//zh-cht.wasa-bi.com">繁体中文</a></li>
<li><a class="fr" href="//fr.wasa-bi.com">Français</a></li>
<li><a class="es" href="//es.wasa-bi.com">Español</a></li>
<li><a class="ko" href="//ko.wasa-bi.com">한국어</a></li>
<li><a class="th" href="//th.wasa-bi.com">ภาษาไทย</a></li>
```
としているんですが(httpなどのprotocolを除外)、

簡体中文を押すと、
http://wasa-bi.com//zh-chs.wasa-bi.com
へ飛んでしまいます。

以前は、
zh-chs.wasa-bi.com
へ飛んでいました。

**Comment by jsand-minimal** [comment]
Issue書いてくれてありがとうございます。このissueの原因はwidgetにありまして、fixを作ってデプロイしましたので今起こっていないです。

**Comment by cyborgninja** [comment]
今度は全てのサブドメインが取られてしまっているようです。

```
<ul>
<li><a class="en" href="//wasa-bi.com" wovn-ignore="">English</a></li>
<li><a class="zh-chs" href="http://wasa-bi.com">簡体中文</a></li>
<li><a class="zh-cht" href="http://wasa-bi.com">繁体中文</a></li>
<li><a class="fr" href="http://wasa-bi.com">Français</a></li>
<li><a class="es" href="http://wasa-bi.com">Español</a></li>
<li><a class="ko" href="http://wasa-bi.com">한국어</a></li>
<li><a class="th" href="http://wasa-bi.com">ภาษาไทย</a></li>
</ul>
```

**Comment by cyborgninja** [comment]
<ul wovn-ignore="">
<li><a class="en" href="//wasa-bi.com">English</a></li>
<li><a class="zh-chs" href="http://wasa-bi.com">簡体中文</a></li>
<li><a class="zh-cht" href="http://wasa-bi.com">繁体中文</a></li>
<li><a class="fr" href="http://wasa-bi.com">Français</a></li>
<li><a class="es" href="http://wasa-bi.com">Español</a></li>
<li><a class="ko" href="http://wasa-bi.com">한국어</a></li>
<li><a class="th" href="http://wasa-bi.com">ภาษาไทย</a></li>
</ul>

で、解決
